name: flutter_myinsta
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  flutter_icons: ^1.1.0
  cached_network_image: ^3.2.0
  favorite_button: ^0.0.4
  insta_like_button: ^0.1.1
  camera: ^0.9.4+5
  local_image_provider: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  path_provider: ^2.0.8
  pop_bottom_menu: ^1.0.0
  flutter_svg: ^1.0.1
  permission_handler: ^8.3.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.13
  toast: ^0.1.5
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  firebase_storage: ^10.2.7
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  image: ^3.1.1
  video_player: ^2.2.19
  screenshot: ^1.2.3
  extension: ^0.4.0
  native_video_view: ^1.0.5
  visibility_detector: ^0.2.2
  video_thumbnail: ^0.4.6
  animated_shimmer: ^1.0.0
  flutter_phosphor_icons: ^0.0.1+6

  


  

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/SVGs/
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
    - family: Billbong_family
      fonts:
        - asset: assets/fonts/Billabong.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
