name: flutter_myinsta
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animated_shimmer: ^1.0.0
  cached_network_image: ^3.2.0
  camera: ^0.9.4+5
  cloud_firestore: ^3.1.8

  cupertino_icons: ^1.0.2
  extension: ^0.4.0
  favorite_button: ^0.0.4
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  flutter_icons: ^1.1.0
  flutter_phosphor_icons: ^0.0.1+6
  flutter_svg: ^1.0.1
  format: ^1.1.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  image: ^3.1.1
  insta_like_button: ^0.1.1
  local_image_provider: ^4.0.1
  modal_bottom_sheet: ^2.0.0
  native_video_view: ^1.0.5
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  pop_bottom_menu: ^1.0.0
  pull_to_refresh: ^2.0.0
  screenshot: ^1.2.3
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2
  toast: ^0.1.5
  video_player: ^2.2.19
  video_thumbnail: ^0.4.6
  visibility_detector: ^0.2.2
  platform_device_id: ^1.0.1
  firebase_messaging: ^11.2.12  
  http: ^0.13.4
  flutter_local_notifications: ^9.4.0
  share_plus: ^4.0.4
  share_extend: 
  



  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/SVGs/
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: Billbong_family
      fonts:
        - asset: assets/fonts/Billabong.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
